---
title: "Discrete Choice Models"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

## Loading the data sets 

```{r}
library(mlogit)
library(Ecdat)

data("Cracker",package="mlogit")
data("Yogurt",package="Ecdat")

```

## Viewing the data 


```{r setup, include=FALSE,echo=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
library(stargazer)
```

```{r mylatextable, results = "asis"}
Yogurtlong<-mlogit.data(Yogurt,shape = "long",varying = 2:9,choice = "choice")
head(Yogurtlong)
names(Yogurtlong)
names(Yogurtlong)[3]<-c("Brand")
Yogurtlong<-Yogurtlong[,2:5]

Yogurtlong$choice[Yogurtlong$choice=="FALSE"]=c(0)
Yogurtlong$choice[Yogurtlong$choice=="TRUE"]=c(1)


```
```{r}
library(dplyr)

MS_tab=summarise(
  group_by(Yogurtlong,Brand),
          mean=mean(choice),
          sd=sd(choice),
            )
Price_tab=summarise(
  group_by(Yogurtlong,Brand),
          mean=mean(price),
          sd=sd(price),
            )

Feat_tab=summarise(
  group_by(Yogurtlong,Brand),
          mean=mean(feat),
          sd=sd(feat),

              )


```




```{r results='asis',echo=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(kableExtra)
kable(MS_tab,digits = 4,caption = "Market Shares: Yogurt data")
kable(Price_tab,digits = 4,caption = "Prices: Yogurt data")
kable(Feat_tab,digits = 4,caption = "Feature: Yogurt data")



```

## Functions in R
```{r}
Prem <- function(beta) {
  return(beta*c(2,6,8)) 
}

Prem(10)


```
1. Ecrire la fonction de vraisemblance dans le cas du modele logit pour les données Yogurt avec une seule variable (Price)
2. Faire un graphique pour comprendre le comportement de cette fonction
3. Où se situe graphiquement son maximum ?
4. Trouver un package qui cherche le maximum numériquement.




